name: Generate SSH Key and Copy Public Key to Remote Server

on: [push]

jobs:
  generate-and-copy-ssh-key:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Generate SSH key pair
      run: |
        ssh-keygen -t rsa -b 4096 -C "admin@gmail.com" -f $HOME/.ssh/id_rsa -N ""
      id: ssh-key

    - name: Copy SSH public key to remote server
      run: |
        scp -r  $HOME/.ssh/id_rsa.pub ubuntu@52.71.33.91:/root/.ssh/authorized_keys
      env:
        SSH_PRIVATE_KEY: $HOME/.ssh/id_rsa

